# Generated by Django 5.2.5 on 2025-08-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=9, verbose_name='Language')),
                ('path', models.CharField(max_length=99)),
                ('title', models.CharField(max_length=99)),
                ('description', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lineo_pages.block')),
                ('content', models.CharField(max_length=99)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('lineo_pages.block',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lineo_pages.block')),
                ('content', models.CharField(max_length=99)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('lineo_pages.block',),
        ),
        migrations.AddField(
            model_name='block',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineo_pages.page'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='block',
            order_with_respect_to='page',
        ),
    ]
